camera_calibration/check_frame_rate: "false"
camera_calibration/record_save: "true"
camera_calibration/calibrate_single_cameras: "true"
camera_calibration/calibrate_stereo: "true"
camera_calibration/test_calibration: "false"
camera_calibration/run_depth_map: "false"
